version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - pip install --upgrade pip

  build:
    commands:
      - echo Running tests...

artifacts:
  files:
    - '**/*'